apiVersion: v1
kind: ConfigMap

metadata:
  name: kronos-config
  namespace: kronos

data:
  APP_NAME: "KRONOS"
  APP_VERSION: "1.0.0"

  DEBUG: "false"

  HOST: "0.0.0.0"
  PORT: "8000"

  LOG_LEVEL: "INFO"

  REDIS_URL: "redis://kronos-redis:6379/0"

  CELERY_BROKER_URL: "redis://kronos-redis:6379/0"
  CELERY_RESULT_BACKEND: "redis://kronos-redis:6379/0"