apiVersion: v1
kind: Secret

metadata:
  name: kronos-secret
  namespace: kronos

type: Opaque

stringData:
  database-url: "postgresql+asyncpg://<POSTGRES_USER>:<POSTGRES_PASSWORD>@kronos-postgres:5432/<POSTGRES_DB>"

  secret-key: "<GENERATE_A_LONG_RANDOM_SECRET_KEY>"

  postgres-user: "<POSTGRES_USER>"
  postgres-password: "<POSTGRES_PASSWORD>"
  postgres-db: "<POSTGRES_DB>"