apiVersion: v1
kind: Secret

metadata:
  name: kronos-secret
  namespace: kronos

type: Opaque

stringData:
  database-url: "postgresql+asyncpg://postgres:22601Siri@kronos-postgres:5432/kronos"

  secret-key: "CHANGE_THIS_TO_A_LONG_RANDOM_SECRET_KEY"

  postgres-user: "postgres"
  postgres-password: "22601Siri"
  postgres-db: "kronos"