apiVersion: apps/v1
kind: Deployment

metadata:
  name: kronos-postgres
  namespace: kronos
  labels:
    app: kronos-postgres

spec:
  replicas: 1

  selector:
    matchLabels:
      app: kronos-postgres

  template:
    metadata:
      labels:
        app: kronos-postgres

    spec:
      containers:
        - name: postgres
          image: postgres:17

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: kronos-secret
                  key: postgres-db

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: kronos-secret
                  key: postgres-user

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kronos-secret
                  key: postgres-password

          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data

          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc