apiVersion: v1
kind: Service

metadata:
  name: kronos-postgres
  namespace: kronos

  labels:
    app: kronos-postgres

spec:
  selector:
    app: kronos-postgres

  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP

  type: ClusterIP