apiVersion: v1
kind: Service

metadata:
  name: kronos-api
  namespace: kronos

  labels:
    app: kronos-api

spec:
  selector:
    app: kronos-api

  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP

  type: ClusterIP